### ISSUE TITLE
How to run fio using comanche?

### ISSUE THREAD

**Issue by somnode** [IBM/comanche#10]
I have successfully built comanche, but I don't know how to run fio with it.

In SPDK, I used this command to run fio.
`LD_PRELOAD=<path/to/spdk>/examples/nvme/fio_plugin/fio_plugin <path/to/fio>/fio <path/to/spdk>/examples/nvme/fio_plugin/example_config.fio`

With SPDK, I specified `spdk` as the ioengine for my fio script. However, I can't figure out what I should specify as the ioengine for comanche. Is there a specific ioengine for comanche to use with fio?

If I use the same command, will there be any difference between using spdk and comanche?

**Comment by fengggli** [comment]
Currently we don't support fio testing yet.
We plan to have the FUSE interface added in Comanche soon and add a IO engine plugin correspondingly . After that it should be capable of doing that.
Best,
