### ISSUE TITLE
Still having issues with flatbuffers

### ISSUE THREAD

**Issue by dwaddington** [IBM/comanche#29]
A fresh build today gave me this...; its not the first time I have hit this problem.  Do we need a branch/tag on the flatbuffer version?

[ 93%] Building CXX object src/fuse/ustack/CMakeFiles/iotest.dir/src/iotest.cpp.o
In file included from /home/danielwaddington/comanche/src/fuse/ustack/src/ustack_client.h:14:0,
                 from /home/danielwaddington/comanche/src/fuse/ustack/src/iotest.cpp:9:
/home/danielwaddington/comanche/build/src/fuse/ustack/src/protocol_generated.h: In member function ‘bool Protocol::ElementMemoryReply::Verify(flatbuffers::Verifier&) const’:
/home/danielwaddington/comanche/build/src/fuse/ustack/src/protocol_generated.h:300:21: error: ‘class flatbuffers::Verifier’ has no member named ‘VerifyString’
            verifier.VerifyString(shmem_id()) &&
                     ^
/home/danielwaddington/comanche/build/src/fuse/ustack/src/protocol_generated.h: In member function ‘bool Protocol::ElementChannelReply::Verify(flatbuffers::Verifier&) const’:
/home/danielwaddington/comanche/build/src/fuse/ustack/src/protocol_generated.h:361:21: error: ‘class flatbuffers::Verifier’ has no member named ‘VerifyString’
            verifier.VerifyString(uipc_id()) &&
                     ^
src/fuse/ustack/CMakeFiles/iotest.dir/build.make:62: recipe for target 'src/fuse/ustack/CMakeFiles/iotest.dir/src/iotest.cpp.o' failed
make[2]: *** [src/fuse/ustack/CMakeFiles/iotest.dir/src/iotest.cpp.o] Error 1
CMakeFiles/Makefile2:3595: recipe for target 'src/fuse/ustack/CMakeFiles/iotest.dir/all' failed
make[1]: *** [src/fuse/ustack/CMakeFiles/iotest.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fengggli** [comment]
1. Git automatically tracks the version(the commit's hash value) when you add the submodules.  You can see from [here](https://github.com/IBM/comanche/tree/unstable/src/lib), the hash value is shown after the folder names in Github. 
2. The hash value will keep the same(that means Github tracks the version of flatbuffers), unless you explicitly update them (e.g. If you run `git submodule update` with the `--remote` option, git update all the "hooks".  This seems to have happened in [this commit](https://github.com/IBM/comanche/commit/b5c2805afd9d1a546be0f48d95f6232378c65eac))
2. Is this a in-source build or out-of-tree build? I tried a fresh out-of-tree build in my side, and it seems ok.

Thanks
