### ISSUE TITLE
Remove compulsory CUDA dependency

### ISSUE THREAD

**Issue by dwaddington** [IBM/comanche#30]
CUDA should not be compulsory. If its not found, then the CUDA components should not be built.

CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Configuring incomplete, errors occurred!

**Comment by fengggli** [comment]
Currently CUDA is already configured as "optional". There are two CUDA usages, and they are all guarded: 
https://github.com/IBM/comanche/blob/ce9cfad36cc7be22ab339099ff7139aff1057b4b/apps/CMakeLists.txt#L8-L11 
And this:
https://github.com/IBM/comanche/blob/ce9cfad36cc7be22ab339099ff7139aff1057b4b/src/lib/CMakeLists.txt#L52-L61

 If CUDA is not found, those two components are not built (but it will still show the "Could NOT find CUDA " warning in the cmake configure step). That's exactly what happens in the the CI, which doesn't have the CUDA environments, see [here](https://travis-ci.com/IBM/comanche/jobs/145213214#L4836-L4848)).

So I think the error
 ``Configuring incomplete, errors occurred`` 
might be referring to the errors happens before the CUDA warning.
Could you provide the full output of the Cmake?  (I think there will be some kind of Cmake Call stack shown in the output of Cmake, when the error happens)
