### ISSUE TITLE
PMDK build depends on libfabric system install

### ISSUE THREAD

**Issue by dwaddington** [IBM/comanche#31]
PMDK depends on a sys present libfabric e.g., /usr/local/lib 

It should use the libfabric in the install prefix /lib

**Comment by dickeycl** [comment]
pmdk uses pkgconfig to locate libraries (such as libfabric). I have added libfabric as a dependency to pmdk and added the install prefix /lib to PKG_CONFIG_PATH in the pmdk build. That should cause pmdk to use the install prefix libfabric.
