### ISSUE TITLE
urgent: kvstore-perf

### ISSUE THREAD

**Issue by dwaddington** [IBM/comanche#42]
Currently for each worker thread, the tool shares a connection (i.e. instance of the storage component created through the factory).  This limits scaling.

What we need is for each worker thread, a new instance of the component is created for that thread.

**Comment by tjanssen3** [comment]
Implemented on fa6f299aa2bff9ea0250428c73b940853e66155b. Passing back to you to verify.

**Comment by dwaddington** [comment]
I think there may be a problem in cleanly closing the sessions in the worker thread.  Currently an exception is generated on the server side as the session abruptly exists.  Can you check your session clean up code for the worker threads?
