### ISSUE TITLE
urgent:kvstore-perf counting path prefix.

### ISSUE THREAD

**Issue by dwaddington** [IBM/comanche#43]
As a temporary measure, pools for Dawn are called "/dev/dax0.0", "/dev/dax0.1", etc.

I'd like to tweak kvstore-perf so that I can provide a prefix (with the --path option?) e.g., "/dev/dax0." and it will add a value counting from 0 for each worker thread.  

Thus for option --path "/dev/dax0."
worker 0 will use path /dev/dax0.0
worker 1 will use path /dev/dax0.1 etc.

This is a temporary measure until we have a dax allocator.

**Comment by tjanssen3** [comment]
Implemented on a312531bcdfb9dbee0b8852e4a650bfe3eadf1d4. 

Details are in the commit message, but I added a new input option --pool_name that'll support this. To get the behavior specified in the Issue example, you can use `--path="/dev/ --pool_name="dax0" --cores="0,1"` and you'll get pools `/dev/dax0.0` and `/dev/dax0.1`. Passing back to Daniel for verification.
